name: Elaine Randolph
favicon: null
layout_spectrum: 0.99129
typography_spectrum: 0.9381
title: "Elaine Randolph Design's  /  Architectural Designer    Colorist"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#302e0b'
    - '#fca929'
    - '#936925'
    - '#9e0f12'
    - '#e7671e'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
