name: Elaine Randolph
favicon: null
layout_spectrum: 0.8686294783838093
typography_spectrum: 0.186243187636137
title: Architectural Design / Colorist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#050404'
    - '#656565'
    - '#d2e19d'
    - '#9aa177'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
